# Number of labels to fetch (optional). Defaults to 100
numLabels: 40
# These labels will not be used even if the issue contains them (optional).
# Pass a blank array if no labels are to be excluded.
# excludeLabels: []
excludeLabels:
  - meta
# custom configuration to override default behaviour
# control explicitly what gets added and when
custom:
  - location: title
    keywords:
      - '[remove domain]'
    labels:
      - remove
  - location: body
    keywords:
      - 'malware domain'
      - 'command and control'
      - 'malware viruses'
      - 'cryptojacking'
      - 'C2'
    labels:
      - malware
  - location: body
    keywords:
      - 'false positive'
      - 'should not be blocked'
      - 'please allow'
      - 'unblock'
      - 'avoid blocking'
      - 'broken website'
      - 'breaks website'
    labels:
      - remove
  - location: body
    keywords:
      - 'phishing domain'
    labels:
      - phishing
  - location: title
    keywords:
      - help request
    labels:
      - support
  - location: title
    keywords:
      - support request
    labels:
      - support
  - location: title
    keywords:
      - help me
    labels:
      - support
  - location: body
    keywords:
      - help needed
    labels:
      - support
  - location: body
    keywords:
      - cookie consent
    labels:
      - cookie consent
  - location: body
    keywords:
      - redirector
    labels: 
      - redirectors
